/* EGR */

#include <hw_types.h>
#include <interrupt.h>
#include <soc_AM335x.h>
#include <hw_gpio_v2.h>
#include "delay_ms.h"
#include "EGR_Cape.h"
#include "GPIO.h"
#include "Conf_mod.h"
#include "EGR_DCMotor.h"


void myGPIO2IsrA(){
	//EGR_PinRead(GPIO_PORT1_PIN2_MODUL, GPIO_PORT1_PIN2) != 0

	EGR_PinWrite(GPIO_H_BRUECKE_MOTOR1_1_MODUL, GPIO_H_BRUECKE_MOTOR1_1, 0);
	EGR_PinWrite(GPIO_H_BRUECKE_MOTOR1_2_MODUL, GPIO_H_BRUECKE_MOTOR1_2, 1);
	EGR_PinWrite(GPIO_H_BRUECKE_MOTOR2_1_MODUL, GPIO_H_BRUECKE_MOTOR2_1, 1);
	EGR_PinWrite(GPIO_H_BRUECKE_MOTOR2_2_MODUL, GPIO_H_BRUECKE_MOTOR2_2, 0);
	configEHRPWM_A(SOC_EPWM_1_REGS, EHRPWM_SET_OUTPUT_LOW, EHRPWM_SET_OUTPUT_LOW);
	configEHRPWM_B(SOC_EPWM_1_REGS, EHRPWM_SET_OUTPUT_HIGH, EHRPWM_SET_OUTPUT_LOW);
	configEHRPWM_A(SOC_EPWM_2_REGS, EHRPWM_SET_OUTPUT_HIGH, EHRPWM_SET_OUTPUT_LOW);
	configEHRPWM_B(SOC_EPWM_2_REGS, EHRPWM_SET_OUTPUT_LOW, EHRPWM_SET_OUTPUT_LOW);
//	configEHRPWM_A(SOC_EPWM_1_REGS, EHRPWM_OUTPUT_TOGGLE, EHRPWM_OUTPUT_TOGGLE);
//	configEHRPWM_B(SOC_EPWM_1_REGS, EHRPWM_OUTPUT_TOGGLE, EHRPWM_OUTPUT_TOGGLE);
	//Loeschen der Interrupt-Flags
	HWREG(SOC_GPIO_2_REGS + GPIO_IRQSTATUS(0)) |= (1 << GPIO_PORT1_PIN2);
}

void myGPIO2IsrB(){
	//EGR_PinRead(GPIO_PORT1_PIN2_MODUL, GPIO_PORT1_PIN2) != 0

	EGR_PinWrite(GPIO_H_BRUECKE_MOTOR1_1_MODUL, GPIO_H_BRUECKE_MOTOR1_1, 1);
	EGR_PinWrite(GPIO_H_BRUECKE_MOTOR1_2_MODUL, GPIO_H_BRUECKE_MOTOR1_2, 0);
	EGR_PinWrite(GPIO_H_BRUECKE_MOTOR2_1_MODUL, GPIO_H_BRUECKE_MOTOR2_1, 0);
	EGR_PinWrite(GPIO_H_BRUECKE_MOTOR2_2_MODUL, GPIO_H_BRUECKE_MOTOR2_2, 1);
	//PWM an Pin A von Motor 1 anlegen
	configEHRPWM_A(SOC_EPWM_1_REGS, EHRPWM_SET_OUTPUT_HIGH, EHRPWM_SET_OUTPUT_LOW);
	configEHRPWM_B(SOC_EPWM_1_REGS, EHRPWM_SET_OUTPUT_LOW, EHRPWM_SET_OUTPUT_LOW);

	configEHRPWM_A(SOC_EPWM_2_REGS, EHRPWM_SET_OUTPUT_LOW, EHRPWM_SET_OUTPUT_LOW);
	configEHRPWM_B(SOC_EPWM_2_REGS, EHRPWM_SET_OUTPUT_HIGH, EHRPWM_SET_OUTPUT_LOW);
//	configEHRPWM_A(SOC_EPWM_1_REGS, EHRPWM_OUTPUT_TOGGLE, EHRPWM_OUTPUT_TOGGLE);
//	configEHRPWM_B(SOC_EPWM_1_REGS, EHRPWM_OUTPUT_TOGGLE, EHRPWM_OUTPUT_TOGGLE);
	//Loeschen der Interrupt-Flags
	HWREG(SOC_GPIO_2_REGS + GPIO_IRQSTATUS(1)) |= (1 << GPIO_PORT1_PIN4);
}


int main() {
	//pinmuxing fuer taster auf steckplatz 1
	PinMuxing(CONF_PORT1_PIN2, 0, 1, 7);
	PinMuxing(CONF_PORT1_PIN4, 0, 1, 7);
	PinMuxing(CONF_PORT1_PIN6, 0, 1, 7);
	//Taster pin als Input
	EGR_GPIODirSet(GPIO_PORT1_PIN2_MODUL,GPIO_PORT1_PIN2, 1);
	EGR_GPIODirSet(GPIO_PORT1_PIN4_MODUL,GPIO_PORT1_PIN4, 1);
	EGR_GPIODirSet(GPIO_PORT1_PIN6_MODUL,GPIO_PORT1_PIN6, 1);

	//pinmuxing fuer MOTOR 1
	PinMuxing(CONF_H_BRUECKE_MOTOR1_1, 1, 0, 7);
	PinMuxing(CONF_H_BRUECKE_MOTOR1_2, 1, 0, 7);
	PinMuxing(CONF_H_BRUECKE_MOTOR1_1, 1, 0, 6);
	PinMuxing(CONF_H_BRUECKE_MOTOR1_2, 1, 0, 6);

	//pinmuxing fuer MOTOR 2
	PinMuxing(CONF_H_BRUECKE_MOTOR2_1, 1, 0, 7);
	PinMuxing(CONF_H_BRUECKE_MOTOR2_2, 1, 0, 7);
	PinMuxing(CONF_H_BRUECKE_MOTOR2_1, 1, 0, 4);
	PinMuxing(CONF_H_BRUECKE_MOTOR2_2, 1, 0, 4);

	// init Motor, set dutycycle
	EHRPWMinitForDCMotor();

	//initialisiere ARM Interrupt COntroller
	IntAINTCInit();

	//Globale Interruptsteuerung aktivieren
	IntMasterIRQEnable();

	//Lokale Interruptquelle aktivieren
	IntSystemEnable(SYS_INT_GPIOINT2A);
	IntSystemEnable(SYS_INT_GPIOINT2B);

	//Registerung der Funktion myGPIO2Isr auf GPIO2-Interrupt A
	IntRegister(SYS_INT_GPIOINT2A, myGPIO2IsrA);
	IntRegister(SYS_INT_GPIOINT2B, myGPIO2IsrB);

	HWREG(SOC_GPIO_2_REGS + GPIO_IRQSTATUS_SET(0)) |= (1 << GPIO_PORT1_PIN2);
	HWREG(SOC_GPIO_2_REGS + GPIO_LEVELDETECT(0)) |= (1 << GPIO_PORT1_PIN2);

	HWREG(SOC_GPIO_2_REGS + GPIO_IRQSTATUS_SET(1)) |= (1 << GPIO_PORT1_PIN4);
	HWREG(SOC_GPIO_2_REGS + GPIO_LEVELDETECT(0)) |= (1 << GPIO_PORT1_PIN4);

//	//Forward mode
    EHRPWMsetDutyCycle(SOC_EPWM_1_REGS, 100);
    EHRPWMsetDutyCycle(SOC_EPWM_2_REGS, 100);
	EGR_PinWrite(GPIO_H_BRUECKE_MOTOR1_1_MODUL, GPIO_H_BRUECKE_MOTOR1_1, 1);
	EGR_PinWrite(GPIO_H_BRUECKE_MOTOR1_2_MODUL, GPIO_H_BRUECKE_MOTOR1_2, 0);
	EGR_PinWrite(GPIO_H_BRUECKE_MOTOR2_1_MODUL, GPIO_H_BRUECKE_MOTOR2_1, 0);
	EGR_PinWrite(GPIO_H_BRUECKE_MOTOR2_2_MODUL, GPIO_H_BRUECKE_MOTOR2_2, 1);

	//PWM an Pin A von Motor 1 anlegen
	configEHRPWM_A(SOC_EPWM_1_REGS, EHRPWM_SET_OUTPUT_HIGH, EHRPWM_SET_OUTPUT_LOW);
	configEHRPWM_B(SOC_EPWM_1_REGS, EHRPWM_SET_OUTPUT_LOW, EHRPWM_SET_OUTPUT_LOW);
	configEHRPWM_A(SOC_EPWM_2_REGS, EHRPWM_SET_OUTPUT_LOW, EHRPWM_SET_OUTPUT_LOW);
	configEHRPWM_B(SOC_EPWM_2_REGS, EHRPWM_SET_OUTPUT_HIGH, EHRPWM_SET_OUTPUT_LOW);


	while (1)
	{

	}
	return 0;
}
